# Generated by Django 4.0.4 on 2022-04-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_album_musician_delete_car_album_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='albums',
        ),
    ]
