# Generated by Django 4.0.4 on 2022-04-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_musician_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='album_covers'),
        ),
    ]
