# Generated by Django 4.0.4 on 2022-04-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_album_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.CharField(max_length=50),
        ),
    ]
